Jenkins lab 2 files update.

diff --git a/CICD/lab02/Jenkinsfile b/CICD/lab02/Jenkinsfile
--- a/CICD/lab02/Jenkinsfile
+++ b/CICD/lab02/Jenkinsfile
@@ -1,56 +1,76 @@
 pipeline {
     agent any
     environment {
-        APP_NAME = "jenkins-lab02"
-        DOCKERHUB_CRED = credentials('dockerhub-creds')
+        IMAGE_REPO = "therealqi"
+        IMAGE_NAME = "jenkins-lab02"
+        IMAGE_TAG = "${BUILD_NUMBER}"
+        WORKDIR = "CICD/lab02"
     }
     stages {
         stage('Run Unit Tests') {
             steps {
-                sh 'mvn test'
+                dir(env.WORKDIR) {
+                    sh 'mvn test'
+                }
             }
         }
         stage('Build App') {
             steps {
-                sh 'mvn package -DskipTests'
+                dir(env.WORKDIR) {
+                    sh 'mvn clean package -DskipTests'
+                }
             }
         }
         stage('Build Docker Image') {
             steps {
-                sh 'docker build -t ${APP_NAME}:${BUILD_NUMBER} .'
+                dir(env.WORKDIR) {
+                    sh 'docker build -t ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG} .'
+                }
             }
         }
         stage('Push Docker Image') {
             steps {
-                sh '''
-                    echo ${DOCKERHUB_CRED_PSW} | docker login -u ${DOCKERHUB_CRED_USR} --password-stdin
-                    docker tag ${APP_NAME}:${BUILD_NUMBER} ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest
-                    docker push ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest
+                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
+                    sh '''
+                    echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin
+                    docker push ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
                 '''
+                }
             }
         }
         stage('Remove Local Docker Image') {
             steps {
-                sh 'docker rmi ${APP_NAME}:${BUILD_NUMBER} || true'
-                sh 'docker rmi ${APP_NAME}:latest || true'
-                sh 'docker rmi ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest || true'
+                sh 'docker rmi ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG} || true'
             }
         }
         stage('Update Deployment YAML') {
             steps {
-                sh 'echo "Editing Deployment YAML"'
+                dir(env.WORKDIR) {
+                    sh '''
+                  sed -i "s|image:.*|image: ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}|g" app-deployment.yaml
+                '''
+                }
             }
         }
         stage('Deploy on K8s') {
             steps {
-                sh 'kubectl get pods -n ivolve'
+                dir(env.WORKDIR) {
+                    sh '''
+                  kubectl apply -f app-deployment.yaml
+                '''
+                }
             }
         }
     }
     post {
-        always { echo "Pipeline finished." }
-        success { echo "Pipeline succeeded!" }
-        failure { echo "Pipeline failed!" }
+        always {
+            echo "Pipeline finished."
+        }
+        success {
+            echo "Pipeline succeeded!"
+        }
+        failure {
+            echo "Pipeline failed!"
+        }
     }
 }
-
